[build]
  base = "frontend"
  publish = "dist"
  command = "pnpm run build"

[context.production]
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
